console.log("=== Assignment 1====");
var myFullName; 
console.log("My Full Name variable value before Initialization:", myFullName);
myFullName="Manisha Mane";
console.log("My Full Name variable value after Initialization:", myFullName);
myFullName="Manisha Prabhakar Mane";
console.log("My Full Name variable value after updation:", myFullName);

console.log("=== Assignment 2 ====");

var myLove;
myLove = "I love only JS";
console.log(myLove);
console.log("=== Assignment 3 ====");
var firstName;
var lastName;
var Age;
var Address;
var Gender;
var isMarried;
firstName = "Manisha";
lastName = "Mane";
Age = 23;
Address = "Pune";
Gender = "Female";
isMarried= "No";
console.log("First name:", firstName);
console.log("Last name:", lastName);
console.log("My Age:", Age );
console.log("My Address:", Address);
console.log("Gender:", Gender);
console.log("Married Status:", isMarried);